/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import controlador.TablasRegistroController;
import controlador.VentanasController;

/**
 *formulario consultar banco que permite consultar las entidades bancarias que
 * se encuentran previamente registradas en el sistema y asi generar o no su 
 * respectivo reporte
 * @author GAMER
 */
public class ConsultarBanco extends javax.swing.JFrame {
    int id_bank=0;
    /**
     * Creates new form ConsultarBanco
     */
    public ConsultarBanco() {
        initComponents();
        TablasRegistroController.llenarTablaBanco(tblbancos);
               this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblbancos = new javax.swing.JTable();
        txtidbanco = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnconsulta = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnreporte = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblbancos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblbancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblbancos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbancosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblbancos);

        txtidbanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtidbanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidbancoKeyTyped(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnconsulta.setBackground(new java.awt.Color(255, 255, 255));
        btnconsulta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnconsulta.setForeground(new java.awt.Color(0, 0, 0));
        btnconsulta.setText("CONSULTAS");
        btnconsulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaActionPerformed(evt);
            }
        });
        jPanel1.add(btnconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 100, 40));

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("INICIO");
        btnInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 100, 40));

        btnreporte.setBackground(new java.awt.Color(255, 255, 255));
        btnreporte.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnreporte.setForeground(new java.awt.Color(0, 0, 0));
        btnreporte.setText("REPORTES");
        btnreporte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 100, 40));

        btnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistro.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistro.setText("REGISTROS");
        btnRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txtidbanco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidbanco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * tabla banco que muestra las entidades bancarias que ya se 
     * encuentran registradas en el sistema
     * @param evt tblbancosMouseClicked
     */
    private void tblbancosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbancosMouseClicked
        int row=tblbancos.getSelectedRow();
        if(row!=-1){
            id_bank=Integer.parseInt(String.valueOf(tblbancos.getModel().getValueAt(row,0)));
            txtidbanco.setText(String.valueOf(id_bank));
        }  
    }//GEN-LAST:event_tblbancosMouseClicked
//CODIGO INSERVIBLE
    private void txtidbancoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidbancoKeyTyped
        // TODO add your handling code here:
       /** if(txtidbanco.getText().length() >= 13 && !Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }**/
    }//GEN-LAST:event_txtidbancoKeyTyped
/**
 * boton Consultas que lleva al submenu de consultas y cierra la ventana de 
 * consultar banco
 * @param evt btnconsultaActionPerformed
 */
    private void btnconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaActionPerformed
VentanasController.abrirSubmenuConsulta();
VentanasController.cerrarConsultarBanco();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconsultaActionPerformed
/**
 * boton Inicio que lleva a la pantalla principal del programa y cierra la ventana de 
 * consultar banco
 * @param evt btnInicioActionPerformed
 */
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
VentanasController.abrirInicio();
VentanasController.cerrarConsultarBanco();
    }//GEN-LAST:event_btnInicioActionPerformed
/**
 * boton reporte que lleva al submenu de reportes y cierra la ventana de 
 * consultar banco
 * @param evt btnreporteActionPerformed
 */
    private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed
VentanasController.abrirReportes();
VentanasController.cerrarConsultarBanco();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreporteActionPerformed
/**
 * boton registro que lleva al submenu de registro y cierra la ventana de 
 * consultar banco
 * @param evt btnRegistroActionPerformed
 */
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
VentanasController.abrirSubmenuRegistro();
VentanasController.cerrarConsultarBanco();
    }//GEN-LAST:event_btnRegistroActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnconsulta;
    private javax.swing.JButton btnreporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblbancos;
    private javax.swing.JTextField txtidbanco;
    // End of variables declaration//GEN-END:variables
}
