/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import controlador.TablasRegistroController;
import controlador.VentanasController;

/**
 *formulario que muestra la tabla cargada con datos del sistema
 * pertenecientes a los registros de presidentes
 * @author GAMER
 */
public class ConsultarPresidente extends javax.swing.JFrame {
    int id_com;
    /**
     * Creates new form ConsultarPresidente
     */
    public ConsultarPresidente() {
        initComponents();
        TablasRegistroController.llenarTablaPresidente(tblpresidentes);
               this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblpresidentes = new javax.swing.JTable();
        txtidpresidente1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnconsultas = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblpresidentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblpresidentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblpresidentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpresidentesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpresidentes);

        txtidpresidente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtidpresidente1.setEnabled(false);
        txtidpresidente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidpresidente1KeyTyped(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnconsultas.setBackground(new java.awt.Color(255, 255, 255));
        btnconsultas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnconsultas.setForeground(new java.awt.Color(0, 0, 0));
        btnconsultas.setText("CONSULTAS");
        btnconsultas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnconsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultasActionPerformed(evt);
            }
        });
        jPanel1.add(btnconsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 100, 40));

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("INICIO");
        btnInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 100, 40));

        btnreportes.setBackground(new java.awt.Color(255, 255, 255));
        btnreportes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnreportes.setForeground(new java.awt.Color(0, 0, 0));
        btnreportes.setText("REPORTES");
        btnreportes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 100, 40));

        btnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistro.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistro.setText("REGISTROS");
        btnRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtidpresidente1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidpresidente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblpresidentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpresidentesMouseClicked
        int row=tblpresidentes.getSelectedRow();
        if(row!=-1){
            id_com=Integer.parseInt(String.valueOf(tblpresidentes.getModel().getValueAt(row,0)));
            txtidpresidente1.setText(String.valueOf(id_com));
        }       // TODO add your handling code here:
    }//GEN-LAST:event_tblpresidentesMouseClicked

    private void txtidpresidente1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpresidente1KeyTyped
        if(txtidpresidente1.getText().length() >= 10 && !Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpresidente1KeyTyped
/**
 * boton consultas que abre la ventana de submenu consultas 
 * y cierra la ventana de consultar  presidentes
 * @param evt java.awt.event.ActionEvent evt
 */
    private void btnconsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultasActionPerformed
VentanasController.abrirSubmenuConsulta();
 VentanasController.cerrarConsultarPresidente();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconsultasActionPerformed
/**
 * boton inicio que lleva a la pantalla principal del sistema
 * y cierra la ventana de consultar presidentes
 * @param evt java.awt.event.ActionEvent evt
 */
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VentanasController.abrirInicio();
        VentanasController.cerrarConsultarPresidente();
    }//GEN-LAST:event_btnInicioActionPerformed
/**
 * boton reportes que abre la ventana de submenu reportes 
 * y cierra la ventana de consultar presidentes
 * @param evt java.awt.event.ActionEvent evt
 */
    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
VentanasController.abrirReportes();
 VentanasController.cerrarConsultarPresidente();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportesActionPerformed
/**
 * boton registros que abre la ventana de submenu registros 
 * y cierra la ventana de consultar presidentes
 * @param evt java.awt.event.ActionEvent evt
 */
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
       VentanasController.abrirSubmenuRegistro();
        VentanasController.cerrarConsultarPresidente();
    }//GEN-LAST:event_btnRegistroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnconsultas;
    private javax.swing.JButton btnreportes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblpresidentes;
    private javax.swing.JTextField txtidpresidente1;
    // End of variables declaration//GEN-END:variables
}
