/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    public static int id_Usuario;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void validarIngreso(){
        if(txtUser.getText().isEmpty()){
            txtUser.setBackground(Color.red);
        }
        if(txtpassword.getText().isEmpty()){
             txtpassword.setBackground(Color.red);
        }
        if(!txtUser.getText().isEmpty()&&!txtpassword.getText().isEmpty()){
        Conexion conect= new Conexion();
        com.mysql.jdbc.Connection conexion2=(com.mysql.jdbc.Connection) conect.getconection();
        PreparedStatement buscador = null;
        ResultSet dato = null;
        //JOptionPane.showMessageDialog(null,txtpassword.getText());
        try{
         buscador= (PreparedStatement) conexion2.prepareStatement("select * from Usuario where usuario=? and contraseña=?");
         buscador.setString(1,txtUser.getText());
         buscador.setString(2,txtpassword.getText());
         dato=buscador.executeQuery();
         if(dato.next())
         {
             String id=dato.getString("id_usuario");

             if(txtUser.getText().equalsIgnoreCase(dato.getString("usuario"))&&txtpassword.getText().equalsIgnoreCase(dato.getString("contraseña")))
             {
                 try{
                    if(dato.getString("tipo_usuario_id").equalsIgnoreCase("1")){
                             System.out.println(id);
                             id_Usuario=Integer.parseInt(id);
                    }else if(dato.getString("tipo_usuario_id").equalsIgnoreCase("2")){
                             System.out.println(id);
                             id_Usuario=Integer.parseInt(id);
                    }
                    dispose();
                    new Inicio().setVisible(true);
                 }catch(Exception e){
                     System.out.println("error de obtener id");
                 }
             }
          }
        }catch(SQLException ex)
        {
            System.err.println("ERROR EN OBTENER DATOS");
        }finally{
            try{buscador.close();} catch (Exception e){}
             try{dato.close();} catch (Exception e){}
             try{conexion2.close();} catch (Exception e){}
        }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jblpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        btnrestaurarpwd = new javax.swing.JButton();
        jbliconlogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblUser.setForeground(new java.awt.Color(73, 80, 87));
        jblUser.setText("Usuario");
        jPanel2.add(jblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 390, 40));

        btnLogin.setBackground(new java.awt.Color(204, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("INICIAR SESIÓN");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 390, 40));

        jblpassword.setForeground(new java.awt.Color(73, 80, 87));
        jblpassword.setText("Contraseña");
        jPanel2.add(jblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 390, 40));

        btnrestaurarpwd.setBackground(new java.awt.Color(204, 255, 255));
        btnrestaurarpwd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnrestaurarpwd.setForeground(new java.awt.Color(0, 0, 0));
        btnrestaurarpwd.setText("Restaurar contraseña");
        btnrestaurarpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnrestaurarpwdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnrestaurarpwdMouseExited(evt);
            }
        });
        btnrestaurarpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaurarpwdActionPerformed(evt);
            }
        });
        jPanel2.add(btnrestaurarpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 200, 40));

        jbliconlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iniciar-sesion (1).png"))); // NOI18N
        jPanel2.add(jbliconlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 70, 120));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("INICIAR SESIÓN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 280, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 450, 490));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Union.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        validarIngreso();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnrestaurarpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaurarpwdActionPerformed
    Restaurar_contraseña restaurar = new Restaurar_contraseña();
    restaurar.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnrestaurarpwdActionPerformed
public void setColor(JButton j){
j.setBackground(new Color(102,255,255));
}
public void resetColor(JButton j1){
j1.setBackground(new Color(204,255,255));
}
    private void btnrestaurarpwdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrestaurarpwdMouseEntered
        setColor(btnrestaurarpwd);
    }//GEN-LAST:event_btnrestaurarpwdMouseEntered

    private void btnrestaurarpwdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrestaurarpwdMouseExited
        resetColor(btnrestaurarpwd);
    }//GEN-LAST:event_btnrestaurarpwdMouseExited

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        setColor(btnLogin);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        resetColor(btnLogin);
    }//GEN-LAST:event_btnLoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnrestaurarpwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jblUser;
    private javax.swing.JLabel jbliconlogin;
    private javax.swing.JLabel jblpassword;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
