/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.VentanasController;

/**
 *
 * @author GAMER
 */
public class Submenu_Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Submenu_Consulta
     */
    public Submenu_Consulta() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        btnRegistro_propietario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnregistro_entbancaria = new javax.swing.JButton();
        btnregistro_presidente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnregistro_finca = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnregistrardirector = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnregistro_gastos_propietarios = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnregistro_cobros = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnreturn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("CONSULTAR PROPIETARIO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 516, 190, -1));

        btnRegistro_propietario.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistro_propietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/propietario.png"))); // NOI18N
        btnRegistro_propietario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegistro_propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_propietarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 436, 100, 80));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("CONSULTAR BANCO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 326, 160, 20));

        btnregistro_entbancaria.setBackground(new java.awt.Color(255, 255, 255));
        btnregistro_entbancaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/entidad bancaria.png"))); // NOI18N
        btnregistro_entbancaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnregistro_entbancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistro_entbancariaActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistro_entbancaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 256, 100, 70));

        btnregistro_presidente.setBackground(new java.awt.Color(255, 255, 255));
        btnregistro_presidente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/presidente (1).png"))); // NOI18N
        btnregistro_presidente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnregistro_presidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistro_presidenteActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistro_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 86, 100, 70));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("CONSULTAR PRESIDENTE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 156, -1, 20));

        btnregistro_finca.setBackground(new java.awt.Color(255, 255, 255));
        btnregistro_finca.setForeground(new java.awt.Color(51, 51, 51));
        btnregistro_finca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/finca.png"))); // NOI18N
        btnregistro_finca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnregistro_finca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistro_fincaActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistro_finca, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 86, 110, 70));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("PAGOS PROPIETARIOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 162, 159, 20));

        btnregistrardirector.setBackground(new java.awt.Color(255, 255, 255));
        btnregistrardirector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jefe.png"))); // NOI18N
        btnregistrardirector.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnregistrardirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrardirectorActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrardirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 259, 110, 70));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText(" GASTOS COMUNIDAD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 329, 160, 20));

        btnregistro_gastos_propietarios.setBackground(new java.awt.Color(255, 255, 255));
        btnregistro_gastos_propietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/metodo-de-pago.png"))); // NOI18N
        btnregistro_gastos_propietarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnregistro_gastos_propietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistro_gastos_propietariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistro_gastos_propietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 449, 110, 70));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("CONSULTAR GASTOS PROPIETARIOS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 525, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText(" COBROS PROPIETARIOS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 330, 183, -1));

        btnregistro_cobros.setBackground(new java.awt.Color(255, 255, 255));
        btnregistro_cobros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cobro.png"))); // NOI18N
        btnregistro_cobros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnregistro_cobros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistro_cobrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistro_cobros, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 254, 110, 70));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnreturn.setBackground(new java.awt.Color(0, 0, 0));
        btnreturn.setForeground(new java.awt.Color(153, 255, 255));
        btnreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/undo.png"))); // NOI18N
        btnreturn.setBorder(null);
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MENU CONSULTA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 370, 80));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REGRESAR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 865, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistro_propietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_propietarioActionPerformed
/**    try{
        VentanasController.abrirConsultarPropietarios();
       
    }catch(Exception e){
         VentanasController.cerrarConsultarPropietarios();
        VentanasController.abrirConsultarPropietarios();
    }**/
VentanasController.abrirConsultarPropietarios();
VentanasController.cerrarSubmenuConsulta();
    }//GEN-LAST:event_btnRegistro_propietarioActionPerformed

    private void btnregistro_entbancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistro_entbancariaActionPerformed
    /**try{
        VentanasController.abrirConsultarBanco();
        
    }catch(Exception e){
        VentanasController.cerrarConsultarBanco();
        VentanasController.abrirConsultarBanco();
    }**/
    VentanasController.abrirConsultarBanco();
    VentanasController.cerrarSubmenuConsulta();
    }//GEN-LAST:event_btnregistro_entbancariaActionPerformed

    private void btnregistro_presidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistro_presidenteActionPerformed
    /**try{
        VentanasController.abrirConsultarPresidente();
    }catch(Exception e){
         VentanasController.cerrarConsultarPresidente();
        VentanasController.abrirConsultarPresidente();
    }**/
    VentanasController.abrirConsultarPresidente();
     VentanasController.cerrarSubmenuConsulta();
    }//GEN-LAST:event_btnregistro_presidenteActionPerformed

    private void btnregistro_fincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistro_fincaActionPerformed
   /** try{
        VentanasController.abrirConsultarPagos();
    }catch(Exception e){
         VentanasController.cerrarConsultarPagos();
        VentanasController.abrirConsultarPagos();
    } **/
   VentanasController.abrirConsultarPagos();
   VentanasController.cerrarSubmenuConsulta();
    }//GEN-LAST:event_btnregistro_fincaActionPerformed

    private void btnregistrardirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrardirectorActionPerformed
/**    try{
        VentanasController.abrirConsultarGastosComunidad();
    }catch(Exception e){
         VentanasController.cerrarConsultarGastosComunidad();
        VentanasController.abrirConsultarGastosComunidad();
    }**/
VentanasController.abrirConsultarGastosComunidad();
VentanasController.cerrarSubmenuConsulta();
    }//GEN-LAST:event_btnregistrardirectorActionPerformed

    private void btnregistro_gastos_propietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistro_gastos_propietariosActionPerformed
/**    try{
        VentanasController.abrirConsultarGastosPropietario();
    }catch(Exception e){
         VentanasController.cerrarConsultarGastosPropietario();
        VentanasController.abrirConsultarGastosPropietario();
    }**/
VentanasController.abrirConsultarGastosPropietario();
    }//GEN-LAST:event_btnregistro_gastos_propietariosActionPerformed

    private void btnregistro_cobrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistro_cobrosActionPerformed
/**    try{
        VentanasController.abrirConsultarCobros();
    }catch(Exception e){
         VentanasController.cerrarConsultarCobros();
        VentanasController.abrirConsultarCobros();
    }**/
VentanasController.abrirConsultarCobros();
VentanasController.cerrarSubmenuConsulta();
    }//GEN-LAST:event_btnregistro_cobrosActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        try{VentanasController.cerrarInicio();}catch(Exception e){}
        VentanasController.abrirInicio();
        VentanasController.cerrarSubmenuConsulta();
    }//GEN-LAST:event_btnreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submenu_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submenu_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submenu_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submenu_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submenu_Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro_propietario;
    private javax.swing.JButton btnregistrardirector;
    private javax.swing.JButton btnregistro_cobros;
    private javax.swing.JButton btnregistro_entbancaria;
    private javax.swing.JButton btnregistro_finca;
    private javax.swing.JButton btnregistro_gastos_propietarios;
    private javax.swing.JButton btnregistro_presidente;
    private javax.swing.JButton btnreturn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
